### ISSUE TITLE
Xss is not working

### ISSUE THREAD

**Issue by Naveenvuedata** [AhmedAdelFahim/express-xss-sanitizer#2]
Hi I have added in one of my projects as middleware it is not working 
const { xss } = require('express-xss-sanitizer');

router.post(
  '/userpost'
  xss(),
  userController.userPost
);

**Comment by AhmedAdelFahim** [comment]
@Naveenvuedata what is the error?

**Comment by AhmedAdelFahim** [comment]
> Hi I have added in one of my projects as middleware it is not working const { xss } = require('express-xss-sanitizer');
> 
> router.post( '/userpost' xss(), userController.userPost );

can you share more data about your problem?

**Comment by Naveenvuedata** [comment]
Like this kindly of the tag are not working in XSS NPM, check this  @AhmedAdelFahim 


`<br/>Tracking<br/>Type: Tracking/Order Status<br/>Last Note:User Details <p></p><br/><script>console.log(test);</script><br/><script>console.log(test2);</script><br/><h3>Tracking History for your order 12324234</h3><br/><br/><p><b>tracking id:12312</b> <a href='https://www.somewebsite.com' target=_blank>12111</a></p><br/><br/><p>Your item arrived </p><br/>`
